src/objects/Auto_Convert_Lead__c.object
<CustomObject>
    <description>Input parameter to the Auto Convert Lead Apex method</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Auto Convert Leads</relationshipLabel>
        <relationshipName>Auto_Convert_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Auto Convert Leads</relationshipLabel>
        <relationshipName>Auto_Convert_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auto Convert Lead</label>
    <nameField>
        <displayFormat>ACL-{0000}</displayFormat>
        <label>Auto Convert Lead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auto Convert Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AutoConvertLeads.cls
// Code example sourced from https://automationchampion.com/tag/auto-convert-lead-using-process-builder/
//
Public class AutoConvertLeads
{
    @InvocableMethod
    public static void LeadAssign(List<Auto_Convert_Lead__c> leads)
    {
        LeadStatus CLeadStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true Limit 1];
        List<Database.LeadConvert> massLeadConvert = new List<Database.LeadConvert>();
        for (Auto_Convert_Lead__c currentLead: leads){
                Database.LeadConvert Leadconvert = new Database.LeadConvert();

                if (String.isBlank(currentLead.Lead__c)) {
                    continue;
                }
                Leadconvert.setLeadId(currentlead.Lead__c);

                if (!String.isBlank(currentLead.Account__c)) {
                    Leadconvert.setAccountId(currentLead.Account__c);                
                }

                Leadconvert.setConvertedStatus(CLeadStatus.MasterLabel);
                Leadconvert.setDoNotCreateOpportunity(TRUE);
                massLeadConvert.add(leadConvert);
        }
        
        if (!massLeadConvert.isEmpty()) {
            List<Database.LeadConvertResult> lcr = Database.convertLead(massLeadConvert);
        }
    }
}